NDefines.NGame. END_DATE = "1970.1.1.1"
NDefines.NGraphics.MINIMUM_PROVINCE_SIZE_IN_PIXELS = 1

NDefines.NGraphics.COUNTRY_FLAG_TEX_MAX_SIZE = 2048
NDefines.NGraphics.COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 512
NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_WIDTH = 10
NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_HEIGHT = 8196
NDefines.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_WIDTH = 41
NDefines.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_HEIGHT = 24000

NDefines.NDiplomacy.MIN_TRUST_VALUE = -500			-- max value for embargo, vanilla -100
NDefines.NAI.RESEARCH_NEW_WEIGHT_FACTOR = 0.25		-- Impact of previously unexplored tech weights. Higher means more random exploration.
NDefines.NAI.RESEARCH_BONUS_FACTOR = 10.0			-- To which extent AI should care about bonuses to research
NDefines.NAI.RESEARCH_AHEAD_OF_TIME_FACTOR = 7.5	-- To which extent AI should care about ahead of time penalties to research
NDefines.NAI.DIVISION_UPGRADE_MIN_XP = 20				-- Minimum XP before attempting to upgrade a division template. #5
NDefines.NAI.DIVISION_CREATE_MIN_XP = 150				-- Minimum XP before attempting to create a fresh new division template. #100
NDefines.NAI.VARIANT_UPGRADE_MIN_XP = 100				-- Minimum XP before attempting to create a new variant. #50
NDefines.NAI.UPGRADE_XP_RUSH_UPDATE = 250				-- If XP is above this on the daily tick the AI will attempt to spend it#150
NDefines.NDiplomacy.RESOURCE_SENT_AUTONOMY_DAILY_FACTOR = 0.001
NDefines.NDiplomacy.WAR_SCORE_AUTONOMY_FACTOR = 0.2
NDefines.NDiplomacy.LL_TO_OVERLORD_AUTONOMY_DAILY_FACTOR = 0.01
NDefines.NDiplomacy.AUTONOMY_FREEDOM_FROM_CAPITULATE = 0.1
NDefines.NDiplomacy.ATTACHE_TO_OVERLORD_EFFECT = 0.01
NDefines.NDiplomacy.ATTACHE_TO_OVERLORD_EFFECT = 0.01
NDefines.NDiplomacy.BASE_TRUCE_PERIOD = 365
NDefines.NDiplomacy.BASE_BOOST_PARTY_POPULARITY_DAILY_PP = 15.0
NDefines.NDiplomacy.BASE_BOOST_PARTY_POPULARITY_DAILY_DRIFT = 0.15
NDefines.NDiplomacy.WARGOAL_JUSTIFY_TENSION_FROM_PRODUCTION = 10
NDefines.NDiplomacy.MIN_WARGOAL_JUSTIFY_COST = 5
NDefines.NDiplomacy.NAP_EXPIRY_MONTHS = 120
NDefines.NDiplomacy.NAP_UNBREAKABLE_MONTHS = 60
NDefines.NDiplomacy.NAP_FORCE_BALANCE_RULE_MONTHS = 20
NDefines.NDiplomacy.BASE_STAGE_COUP_DAILY_PP = 30
NDefines.NDiplomacy.GUARANTEE_COST = 50
NDefines.NDiplomacy.REVOKE_GUARANTEE_COST = 100
NDefines.NDiplomacy.TENSION_GENERATE_WARGOAL = 0.5
NDefines.NProduction.BASE_FACTORY_SPEED = 4.25		-- 5
NDefines.NProduction.BASE_FACTORY_SPEED_MIL = 3.75		-- 4.5
NDefines.NAir.STRATEGIC_BOMBER_NUKE_AIR_SUPERIORITY = 0.9		-- How much air superiority is needed for a tactical bomber to be able to nuke a province 0.75
NDefines.NAir.NUKE_DELAY_HOURS = 60
NDefines.NAI.MAX_DISTANCE_NALAV_INVASION = 300.0				-- AI is extremely unwilling to plan naval invasions above this naval distance limit. #200
NDefines.NAI.ENEMY_NAVY_STRENGTH_DONT_BOTHER = 4				-- If the enemy has a navy at least these many times stronger that the own, don't bother invading #2.5
